#include <QApplication>
#include <QFontDatabase>
#include "ui/mainwindow/TabbedMainWindow.h"

int main(int argc,char *argv[])
{
    QApplication app(argc, argv);
    app.setStyle("Fusion");

    const QStringList preferredFonts = {
        "Fira Sans",
        "Source Sans 3",
        "Noto Sans"
    };
    QString selectedFont;
    const auto families = QFontDatabase().families();
    for (const auto &family : preferredFonts) {
        if (families.contains(family)) {
            selectedFont = family;
            break;
        }
    }
    if (!selectedFont.isEmpty()) {
        QFont appFont(selectedFont, 10);
        app.setFont(appFont);
    }

    app.setStyleSheet(
        "QMainWindow {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #F4F6F9, stop:1 #E9EDF2);"
        "}"
        "QWidget {"
        "  color: #383A42;"
        "  background-color: #FAFBFC;"
        "}"
        "QLabel {"
        "  color: #4B515D;"
        "  font-size: 12px;"
        "}"
        "QMenuBar {"
        "  background-color: #EDEFF3;"
        "  padding: 6px 10px;"
        "}"
        "QMenuBar::item {"
        "  background: transparent;"
        "  padding: 6px 12px;"
        "  border-radius: 6px;"
        "}"
        "QMenuBar::item:selected {"
        "  background-color: #E1E6EE;"
        "}"
        "QMenu {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  padding: 6px;"
        "}"
        "QMenu::item {"
        "  padding: 6px 12px;"
        "  border-radius: 6px;"
        "}"
        "QMenu::item:selected {"
        "  background-color: #E7F0FC;"
        "  color: #4078F2;"
        "}"
        "QToolBar {"
        "  background-color: #EEF1F5;"
        "  border: 1px solid #D3D8E0;"
        "  padding: 6px 8px;"
        "  spacing: 6px;"
        "}"
        "QToolBar::separator {"
        "  background: #D3D8E0;"
        "  width: 1px;"
        "  margin: 4px 6px;"
        "}"
        "QToolButton {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 6px 10px;"
        "  min-height: 28px;"
        "}"
        "QToolButton:hover {"
        "  background-color: #EDF4FF;"
        "  border-color: #AFC7F3;"
        "}"
        "QToolButton:pressed {"
        "  background-color: #DCE8FF;"
        "  border-color: #8FB0EF;"
        "}"
        "QToolButton:checked {"
        "  background-color: #E1EDFF;"
        "  border-color: #7DA2EE;"
        "}"
        "QPushButton {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 6px 12px;"
        "  min-height: 30px;"
        "}"
        "QPushButton:hover {"
        "  background-color: #EDF4FF;"
        "  border-color: #AFC7F3;"
        "}"
        "QPushButton:pressed {"
        "  background-color: #DCE8FF;"
        "  border-color: #8FB0EF;"
        "}"
        "QPushButton#algorithmButton {"
        "  padding: 5px 10px;"
        "  min-width: 96px;"
        "  max-width: 132px;"
        "}"
        "QToolBar#algorithmToolBar {"
        "  padding: 4px 8px;"
        "}"
        "QComboBox {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 4px 10px;"
        "  min-height: 28px;"
        "  min-width: 120px;"
        "}"
        "QComboBox:hover {"
        "  border-color: #B9C0CB;"
        "}"
        "QComboBox::drop-down {"
        "  border: none;"
        "  width: 24px;"
        "}"
        "QComboBox QAbstractItemView {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  selection-background-color: #E7F0FC;"
        "  selection-color: #4078F2;"
        "  padding: 4px;"
        "}"
        "QToolBox {"
        "  background-color: #EEF1F5;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 10px;"
        "}"
        "QToolBox::tab {"
        "  background: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 14px 18px;"
        "  margin: 4px;"
        "  min-height: 76px;"
        "  min-width: 260px;"
        "  font-weight: 600;"
        "  font-size: 14px;"
        "  text-align: left;"
        "}"
        "QToolBox::tab:selected {"
        "  background: #E7F0FC;"
        "  border-color: #AFC7F3;"
        "}"
        "QTabWidget::pane {"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 12px;"
        "  background: #F1F4F8;"
        "}"
        "QTabBar::tab {"
        "  background: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  padding: 6px 12px;"
        "  border-top-left-radius: 8px;"
        "  border-top-right-radius: 8px;"
        "  margin-right: 4px;"
        "  min-width: 120px;"
        "}"
        "QTabBar::tab:selected {"
        "  background: #E7F0FC;"
        "  border-color: #AFC7F3;"
        "}"
        "QTabBar::tab:!selected {"
        "  margin-top: 2px;"
        "}"
        "QGraphicsView {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 10px;"
        "}"
        "QLineEdit {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 4px 8px;"
        "  min-height: 26px;"
        "}"
        "QCheckBox {"
        "  spacing: 6px;"
        "}"
        "QScrollArea {"
        "  background: #FAFBFC;"
        "  border: none;"
        "}"
        "QScrollBar:vertical {"
        "  background: #E6EAF0;"
        "  width: 10px;"
        "  margin: 2px;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background: #C5CCD6;"
        "  border-radius: 5px;"
        "  min-height: 20px;"
        "}"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "  height: 0px;"
        "}"
        "QListView, QTableView {"
        "  background-color: #FFFFFF;"
        "  alternate-background-color: #F2F4F8;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "}"
        "QHeaderView::section {"
        "  background-color: #EEF1F5;"
        "  color: #4B515D;"
        "  padding: 4px 8px;"
        "  border: none;"
        "}"
        "QAbstractItemView::item:selected {"
        "  background-color: #E7F0FC;"
        "  color: #4078F2;"
        "}"
        "QTextEdit, QPlainTextEdit {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "  padding: 4px 6px;"
        "}"
        "QSplitter::handle {"
        "  background-color: #D3D8E0;"
        "}"
        "CustomStatusBar {"
        "  background-color: #FFFFFF;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 10px;"
        "  min-height: 120px;"
        "}"
        "QLabel#statusMessage {"
        "  background: transparent;"
        "  border: none;"
        "  padding: 3px 8px;"
        "  color: #2F343C;"
        "  font-size: 13px;"
        "  font-weight: 600;"
        "}"
        "QWidget#operationStatus {"
        "  background-color: #F4F7FB;"
        "  border: 1px solid #D3D8E0;"
        "  border-radius: 8px;"
        "}"
        "QProgressBar {"
        "  border: 1px solid #C5CCD6;"
        "  border-radius: 6px;"
        "  background-color: #EEF2F6;"
        "}"
        "QProgressBar::chunk {"
        "  border-radius: 5px;"
        "  background-color: #4078F2;"
        "}"
    );

    TabbedMainWindow mainWindow;
    mainWindow.show();

    return app.exec();
}
