"""Size-independent graph actor/critic for layout-compaction actions.

Unlike the legacy flat MLP, this policy has no node-count, layer-count, or
action-count in its parameter shapes.  It encodes a directed circuit graph and
scores the legal action candidates generated by the environment at runtime.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Any, Sequence

import torch
from torch import nn
from torch.distributions import Categorical

try:
    from .stochastic_clock import ClockField
except ImportError:  # Supports the project's current top-level ``src`` import style.
    from stochastic_clock import ClockField


GATE_TYPE_NAMES = (
    "input",
    "output",
    "maj",
    "and",
    "or",
    "not",
    "redundancy",
    "fanout",
)
NODE_FEATURE_DIM = 26
EDGE_FEATURE_DIM = 10
ACTION_FEATURE_DIM = 4
CLOCK_FEATURE_DIM = 15
RETRIEVAL_FEATURE_DIM = 32
EPISODE_FEATURE_DIM = 12
ROUTE_AUX_FEATURE_DIM = 10


class LayoutActionType(IntEnum):
    NOOP = 0
    GAP = 1
    LAYER_PRIMARY_SHIFT = 2
    LAYER_BLOCK_PRIMARY_SHIFT = 3
    LAYER_BLOCK_SHIFT = 4
    SEGMENT_SHIFT = 5
    LAYER_SHIFT = 6
    NODE_SHIFT = 7
    REROUTE_NET = 8


_ACTION_TYPE_BY_NAME = {
    "noop": LayoutActionType.NOOP,
    "gap": LayoutActionType.GAP,
    "layer_primary_shift": LayoutActionType.LAYER_PRIMARY_SHIFT,
    "layer_block_primary_shift": LayoutActionType.LAYER_BLOCK_PRIMARY_SHIFT,
    "layer_block_shift": LayoutActionType.LAYER_BLOCK_SHIFT,
    "segment_shift": LayoutActionType.SEGMENT_SHIFT,
    "layer_shift": LayoutActionType.LAYER_SHIFT,
    "node_shift": LayoutActionType.NODE_SHIFT,
    "reroute_net": LayoutActionType.REROUTE_NET,
}


@dataclass(frozen=True)
class GraphPolicyInput:
    """One graph state and its ragged action candidate list."""

    node_features: torch.Tensor
    edge_index: torch.Tensor
    edge_features: torch.Tensor
    clock_features: torch.Tensor
    action_types: torch.Tensor
    action_features: torch.Tensor
    action_target_index: torch.Tensor
    action_mask: torch.Tensor
    retrieval_features: torch.Tensor | None = None
    episode_features: torch.Tensor | None = None
    memory_state: torch.Tensor | None = None

    def validate(self) -> None:
        if self.node_features.ndim != 2 or self.node_features.shape[0] <= 0:
            raise ValueError("node_features must have shape [num_nodes, feature_dim]")
        if self.edge_index.ndim != 2 or self.edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape [2, num_edges]")
        if self.edge_features.ndim != 2 or self.edge_features.shape[0] != self.edge_index.shape[1]:
            raise ValueError("edge_features must have shape [num_edges, feature_dim]")
        if self.clock_features.ndim != 1:
            raise ValueError("clock_features must be one-dimensional")
        if self.action_types.ndim != 1 or self.action_types.shape[0] <= 0:
            raise ValueError("action_types must contain at least one candidate")
        action_count = int(self.action_types.shape[0])
        if self.action_features.ndim != 2 or self.action_features.shape[0] != action_count:
            raise ValueError("action_features must have shape [num_actions, feature_dim]")
        if self.action_target_index.ndim != 2 or self.action_target_index.shape[0] != 2:
            raise ValueError("action_target_index must have shape [2, num_memberships]")
        if self.action_mask.shape != (action_count,):
            raise ValueError("action_mask must have shape [num_actions]")
        if not bool(torch.any(self.action_mask)):
            raise ValueError("at least one action must be legal")
        if self.edge_index.numel():
            if int(self.edge_index.min()) < 0 or int(self.edge_index.max()) >= self.node_features.shape[0]:
                raise ValueError("edge_index contains an invalid node index")
        if self.action_target_index.numel():
            action_indices, node_indices = self.action_target_index
            if int(action_indices.min()) < 0 or int(action_indices.max()) >= action_count:
                raise ValueError("action_target_index contains an invalid action index")
            if int(node_indices.min()) < 0 or int(node_indices.max()) >= self.node_features.shape[0]:
                raise ValueError("action_target_index contains an invalid node index")
        for name, value in (
            ("retrieval_features", self.retrieval_features),
            ("episode_features", self.episode_features),
            ("memory_state", self.memory_state),
        ):
            if value is not None and value.ndim != 1:
                raise ValueError(f"{name} must be one-dimensional when provided")

    def to(self, device: torch.device | str) -> "GraphPolicyInput":
        return GraphPolicyInput(
            node_features=self.node_features.to(device),
            edge_index=self.edge_index.to(device),
            edge_features=self.edge_features.to(device),
            clock_features=self.clock_features.to(device),
            action_types=self.action_types.to(device),
            action_features=self.action_features.to(device),
            action_target_index=self.action_target_index.to(device),
            action_mask=self.action_mask.to(device),
            retrieval_features=(
                self.retrieval_features.to(device)
                if self.retrieval_features is not None
                else None
            ),
            episode_features=(
                self.episode_features.to(device)
                if self.episode_features is not None
                else None
            ),
            memory_state=(
                self.memory_state.to(device)
                if self.memory_state is not None
                else None
            ),
        )


class DirectedMessageBlock(nn.Module):
    """Residual directed message passing without a torch-geometric dependency."""

    def __init__(self, hidden_dim: int, dropout: float = 0.0):
        super().__init__()
        self.self_projection = nn.Linear(hidden_dim, hidden_dim)
        self.incoming_projection = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.outgoing_projection = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.incoming_edge_projection = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.outgoing_edge_projection = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.update = nn.Sequential(
            nn.Linear(hidden_dim * 3, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, hidden_dim),
        )
        self.norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(float(dropout))

    @staticmethod
    def _mean_aggregate(
        messages: torch.Tensor,
        destinations: torch.Tensor,
        node_count: int,
    ) -> torch.Tensor:
        output = messages.new_zeros((int(node_count), messages.shape[-1]))
        counts = messages.new_zeros((int(node_count), 1))
        if messages.numel():
            output.index_add_(0, destinations, messages)
            counts.index_add_(
                0,
                destinations,
                torch.ones((destinations.shape[0], 1), dtype=messages.dtype, device=messages.device),
            )
        return output / counts.clamp_min(1.0)

    def forward(
        self,
        node_state: torch.Tensor,
        edge_index: torch.Tensor,
        edge_state: torch.Tensor,
    ) -> torch.Tensor:
        node_count = int(node_state.shape[0])
        if edge_index.numel():
            source, target = edge_index
            incoming = self._mean_aggregate(
                self.incoming_projection(node_state[source])
                + self.incoming_edge_projection(edge_state),
                target,
                node_count,
            )
            outgoing = self._mean_aggregate(
                self.outgoing_projection(node_state[target])
                + self.outgoing_edge_projection(edge_state),
                source,
                node_count,
            )
        else:
            incoming = torch.zeros_like(node_state)
            outgoing = torch.zeros_like(node_state)
        update = self.update(
            torch.cat((self.self_projection(node_state), incoming, outgoing), dim=-1)
        )
        return self.norm(node_state + self.dropout(update))


class UniversalGraphPolicy(nn.Module):
    """Directed GNN actor with dynamic candidate scoring and a pooled critic."""

    def __init__(
        self,
        node_feature_dim: int = NODE_FEATURE_DIM,
        edge_feature_dim: int = EDGE_FEATURE_DIM,
        clock_feature_dim: int = CLOCK_FEATURE_DIM,
        action_feature_dim: int = ACTION_FEATURE_DIM,
        action_type_count: int = len(LayoutActionType),
        retrieval_feature_dim: int = RETRIEVAL_FEATURE_DIM,
        episode_feature_dim: int = EPISODE_FEATURE_DIM,
        memory_dim: int = 64,
        hidden_dim: int = 128,
        message_passing_steps: int = 3,
        dropout: float = 0.0,
    ):
        super().__init__()
        hidden_dim = int(hidden_dim)
        if hidden_dim < 16:
            raise ValueError("hidden_dim must be at least 16")
        self.node_feature_dim = int(node_feature_dim)
        self.edge_feature_dim = int(edge_feature_dim)
        self.clock_feature_dim = int(clock_feature_dim)
        self.action_feature_dim = int(action_feature_dim)
        self.action_type_count = int(action_type_count)
        self.retrieval_feature_dim = int(retrieval_feature_dim)
        self.episode_feature_dim = int(episode_feature_dim)
        self.memory_dim = int(memory_dim)
        self.hidden_dim = hidden_dim
        self.message_passing_steps = max(1, int(message_passing_steps))

        self.node_encoder = nn.Sequential(
            nn.Linear(self.node_feature_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
        )
        self.edge_encoder = nn.Sequential(
            nn.Linear(self.edge_feature_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
        )
        self.message_blocks = nn.ModuleList(
            DirectedMessageBlock(hidden_dim, dropout=dropout)
            for _ in range(self.message_passing_steps)
        )
        self.clock_encoder = nn.Sequential(
            nn.Linear(self.clock_feature_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.graph_encoder = nn.Sequential(
            nn.Linear(hidden_dim * 3, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.LayerNorm(hidden_dim),
        )
        self.retrieval_encoder = nn.Sequential(
            nn.Linear(self.retrieval_feature_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
        )
        self.episode_encoder = nn.Sequential(
            nn.Linear(self.episode_feature_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
        )
        self.memory_cell = nn.GRUCell(hidden_dim * 3, self.memory_dim)
        self.memory_fusion = nn.Sequential(
            nn.Linear(hidden_dim * 2 + self.memory_dim, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.LayerNorm(hidden_dim),
        )
        type_dim = max(8, hidden_dim // 4)
        feature_dim = max(8, hidden_dim // 4)
        self.action_type_embedding = nn.Embedding(self.action_type_count, type_dim)
        self.action_feature_encoder = nn.Sequential(
            nn.Linear(self.action_feature_dim, feature_dim),
            nn.GELU(),
            nn.Linear(feature_dim, feature_dim),
        )
        actor_input_dim = hidden_dim * 2 + type_dim + feature_dim + 1
        self.actor = nn.Sequential(
            nn.Linear(actor_input_dim, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
        )
        self.critic = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
        )
        self.placement_head = nn.Sequential(
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 2),
            nn.Tanh(),
        )
        self.route_head = nn.Sequential(
            nn.Linear(hidden_dim * 4, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, ROUTE_AUX_FEATURE_DIM),
        )
        self.quality_head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
        )

    def initial_memory_state(
        self,
        device: torch.device | str | None = None,
    ) -> torch.Tensor:
        parameter = next(self.parameters())
        return torch.zeros(
            self.memory_dim,
            dtype=parameter.dtype,
            device=parameter.device if device is None else device,
        )

    @staticmethod
    def _optional_vector(
        value: torch.Tensor | None,
        size: int,
        reference: torch.Tensor,
        name: str,
    ) -> torch.Tensor:
        if value is None:
            return reference.new_zeros((int(size),))
        if value.shape != (int(size),):
            raise ValueError(f"{name} dimension does not match the policy")
        return value.to(dtype=reference.dtype, device=reference.device)

    def _encode_state(self, policy_input: GraphPolicyInput) -> dict[str, torch.Tensor]:
        policy_input.validate()
        if policy_input.node_features.shape[-1] != self.node_feature_dim:
            raise ValueError("node feature dimension does not match the policy")
        if policy_input.edge_features.shape[-1] != self.edge_feature_dim:
            raise ValueError("edge feature dimension does not match the policy")
        if policy_input.clock_features.shape[0] != self.clock_feature_dim:
            raise ValueError("clock feature dimension does not match the policy")
        if policy_input.action_features.shape[-1] != self.action_feature_dim:
            raise ValueError("action feature dimension does not match the policy")

        node_state = self.node_encoder(policy_input.node_features)
        edge_state = self.edge_encoder(policy_input.edge_features)
        for block in self.message_blocks:
            node_state = block(node_state, policy_input.edge_index, edge_state)

        graph_mean = node_state.mean(dim=0)
        graph_max = node_state.max(dim=0).values
        clock_state = self.clock_encoder(policy_input.clock_features)
        graph_state = self.graph_encoder(
            torch.cat((graph_mean, graph_max, clock_state), dim=-1)
        )
        retrieval_features = self._optional_vector(
            policy_input.retrieval_features,
            self.retrieval_feature_dim,
            graph_state,
            "retrieval feature",
        )
        episode_features = self._optional_vector(
            policy_input.episode_features,
            self.episode_feature_dim,
            graph_state,
            "episode feature",
        )
        previous_memory = self._optional_vector(
            policy_input.memory_state,
            self.memory_dim,
            graph_state,
            "episode memory",
        )
        retrieval_state = self.retrieval_encoder(retrieval_features)
        episode_state = self.episode_encoder(episode_features)
        next_memory = self.memory_cell(
            torch.cat((graph_state, retrieval_state, episode_state), dim=-1).unsqueeze(0),
            previous_memory.unsqueeze(0),
        ).squeeze(0)
        policy_state = self.memory_fusion(
            torch.cat((graph_state, retrieval_state, next_memory), dim=-1)
        )
        return {
            "node_state": node_state,
            "edge_state": edge_state,
            "graph_state": graph_state,
            "policy_state": policy_state,
            "next_memory": next_memory,
        }

    @staticmethod
    def _pool_action_targets(
        node_state: torch.Tensor,
        action_target_index: torch.Tensor,
        action_count: int,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        pooled = node_state.new_zeros((int(action_count), node_state.shape[-1]))
        counts = node_state.new_zeros((int(action_count), 1))
        if action_target_index.numel():
            action_indices, node_indices = action_target_index
            pooled.index_add_(0, action_indices, node_state[node_indices])
            counts.index_add_(
                0,
                action_indices,
                torch.ones((action_indices.shape[0], 1), dtype=node_state.dtype, device=node_state.device),
            )
        return pooled / counts.clamp_min(1.0), (counts > 0).to(node_state.dtype)

    def forward_with_memory(
        self,
        policy_input: GraphPolicyInput,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        encoded = self._encode_state(policy_input)
        node_state = encoded["node_state"]
        policy_state = encoded["policy_state"]

        action_count = int(policy_input.action_types.shape[0])
        target_state, has_target = self._pool_action_targets(
            node_state,
            policy_input.action_target_index,
            action_count,
        )
        type_state = self.action_type_embedding(policy_input.action_types)
        feature_state = self.action_feature_encoder(policy_input.action_features)
        repeated_graph = policy_state.unsqueeze(0).expand(action_count, -1)
        actor_input = torch.cat(
            (repeated_graph, target_state, type_state, feature_state, has_target),
            dim=-1,
        )
        logits = self.actor(actor_input).squeeze(-1)
        logits = logits.masked_fill(~policy_input.action_mask, torch.finfo(logits.dtype).min)
        value = self.critic(policy_state).squeeze(-1)
        return logits, value, encoded["next_memory"]

    def forward(self, policy_input: GraphPolicyInput) -> tuple[torch.Tensor, torch.Tensor]:
        logits, value, _next_memory = self.forward_with_memory(policy_input)
        return logits, value

    def distribution(self, policy_input: GraphPolicyInput) -> tuple[Categorical, torch.Tensor]:
        logits, value = self(policy_input)
        return Categorical(logits=logits), value

    def distribution_with_memory(
        self,
        policy_input: GraphPolicyInput,
    ) -> tuple[Categorical, torch.Tensor, torch.Tensor]:
        logits, value, next_memory = self.forward_with_memory(policy_input)
        return Categorical(logits=logits), value, next_memory

    def auxiliary_predictions(self, policy_input: GraphPolicyInput) -> dict[str, torch.Tensor]:
        """Predictions used by IFCN offline pretraining and fast layout ranking."""

        encoded = self._encode_state(policy_input)
        node_state = encoded["node_state"]
        edge_state = encoded["edge_state"]
        policy_state = encoded["policy_state"]
        repeated_policy = policy_state.unsqueeze(0).expand(node_state.shape[0], -1)
        placement = self.placement_head(torch.cat((node_state, repeated_policy), dim=-1))
        if policy_input.edge_index.numel():
            source, target = policy_input.edge_index
            repeated_edge_policy = policy_state.unsqueeze(0).expand(source.shape[0], -1)
            route_input = torch.cat(
                (
                    node_state[source],
                    node_state[target],
                    edge_state,
                    repeated_edge_policy,
                ),
                dim=-1,
            )
            route = self.route_head(route_input)
        else:
            route = node_state.new_empty((0, ROUTE_AUX_FEATURE_DIM))
        return {
            "placement": placement,
            "route": route,
            "quality": self.quality_head(policy_state).squeeze(-1),
            "next_memory": encoded["next_memory"],
        }


def _normalize_action_name(name: Any) -> str:
    normalized = str(name).strip().lower()
    return normalized[2:] if normalized.startswith("u_") else normalized


def _normalize_layers(ordered_layers: Any) -> list[list[int]]:
    if isinstance(ordered_layers, dict):
        return [
            [int(node_id) for node_id in ordered_layers[layer_idx]]
            for layer_idx in sorted(ordered_layers)
        ]
    return [[int(node_id) for node_id in layer] for layer in ordered_layers]


def _target_nodes_for_action(
    action_def: tuple[Any, Any, Any],
    layers: Sequence[Sequence[int]],
    node_id_set: set[int],
) -> list[int]:
    action_name, target, _delta = action_def
    action_name = _normalize_action_name(action_name)
    if action_name in ("noop", "reroute_net"):
        return []
    if action_name == "gap":
        boundary = int(target)
        if 0 <= boundary < len(layers) - 1:
            return list(layers[boundary]) + list(layers[boundary + 1])
        return []
    if action_name in ("layer_primary_shift", "layer_shift"):
        layer_idx = int(target)
        return list(layers[layer_idx]) if 0 <= layer_idx < len(layers) else []
    if action_name in ("layer_block_primary_shift", "layer_block_shift"):
        layer_indices = target if isinstance(target, (tuple, list)) else (target,)
        return [
            int(node_id)
            for layer_idx in layer_indices
            if 0 <= int(layer_idx) < len(layers)
            for node_id in layers[int(layer_idx)]
        ]
    if action_name == "segment_shift":
        node_ids = target if isinstance(target, (tuple, list)) else (target,)
        return [int(node_id) for node_id in node_ids if int(node_id) in node_id_set]
    if action_name == "node_shift":
        return [int(target)] if int(target) in node_id_set else []
    return []


def _gate_type_index(type_name: str) -> int | None:
    normalized = str(type_name).strip().lower()
    for index, candidate in enumerate(GATE_TYPE_NAMES):
        if normalized == candidate or normalized.endswith(f".{candidate}"):
            return index
    return None


def _build_clock_features(env: Any, field: ClockField | None) -> torch.Tensor:
    orientation = str(getattr(env, "orientation", ""))
    base = [
        float(getattr(env, "phase_cycle", 4)) / 4.0,
        float(getattr(env, "max_same_phase", 0)) / 8.0,
        float(getattr(env, "padding", 0)) / 8.0,
        float(orientation == "left-right"),
        float(orientation == "top-down"),
    ]
    field_features = list(field.descriptor()) if field is not None else [0.0] * 10
    return torch.tensor(base + field_features, dtype=torch.float32)


def build_clock_features(env: Any, field: ClockField | None) -> torch.Tensor:
    """Public clock-context adapter shared by policy and retrieval memory."""

    return _build_clock_features(env, field)


def build_episode_feedback_features(
    env: Any,
    info: dict[str, Any] | None = None,
    *,
    reward: float = 0.0,
    step_index: int = 0,
    max_steps: int | None = None,
) -> torch.Tensor:
    """Encode the last action outcome consumed by the episode GRU.

    The initial step passes ``info=None`` and therefore receives an all-zero
    outcome except for its (zero) progress.  Exact retrieval context remains
    separate and frozen for the complete episode.
    """

    info = info or {}
    edge_count = max(1, len(getattr(env.circuit, "effective_edges", ())))
    initial_area = max(1.0, float(getattr(env, "initial_result", {}).get("area", 1.0)))
    current_area = float(
        info.get(
            "area",
            getattr(env, "current_result", {}).get("area", initial_area),
        )
    )
    total_steps = max(1, int(max_steps or getattr(env, "max_steps", 1)))
    values = [
        float(torch.tanh(torch.tensor(float(reward) / 10.0)).item()),
        float(bool(info.get("invalid_action", False))),
        float(bool(info.get("accepted_action", False))) if info else 0.0,
        float(bool(info.get("rollback_action", False))),
        float(float(info.get("reward_improvement_bonus", 0.0)) > 0.0),
        float(info.get("reward_delta_clipped", 0.0)) / 4.0,
        float(info.get("reward_area_delta_clipped", 0.0)) / 4.0,
        float(info.get("candidate_failed_edges", info.get("failed_edges", 0))) / edge_count,
        float(info.get("direction_violation_count", 0)) / edge_count,
        float(max(-2.0, min(2.0, current_area / initial_area - 1.0))),
        float(step_index) / float(total_steps),
        float(info.get("action_delta", 0.0)) / 6.0,
    ]
    return torch.tensor(values, dtype=torch.float32)


def build_graph_policy_input(
    env: Any,
    field: ClockField | None = None,
    *,
    retrieval_features: torch.Tensor | Sequence[float] | None = None,
    episode_features: torch.Tensor | Sequence[float] | None = None,
    memory_state: torch.Tensor | Sequence[float] | None = None,
    retrieval_node_hints: dict[int, Sequence[float]] | None = None,
) -> GraphPolicyInput:
    """Adapt the current ``LayoutCompactionEnv`` state without changing it.

    The adapter deliberately consumes the environment's dynamic action list.  A
    future universal trainer can therefore reuse all existing geometric legality
    checks while replacing only the fixed-size observation and MLP policy.
    """

    node_ids = [int(node_id) for node_id in env.node_ids]
    if not node_ids:
        raise ValueError("the environment contains no nodes")
    node_to_index = {node_id: index for index, node_id in enumerate(node_ids)}
    layers = _normalize_layers(env.ordered_layers)
    node_to_layer = {
        int(node_id): int(layer_idx)
        for layer_idx, layer in enumerate(layers)
        for node_id in layer
    }
    positions = {
        int(node_id): (int(coord[0]), int(coord[1]))
        for node_id, coord in env.current_positions.items()
    }
    coord_norm = max(1.0, float(getattr(env, "coord_norm", 1.0)))
    center_x = sum(coord[0] for coord in positions.values()) / float(len(positions))
    center_y = sum(coord[1] for coord in positions.values()) / float(len(positions))
    placed_stages = {
        node_id: int(field.stage_at(coord))
        for node_id, coord in positions.items()
        if field is not None and coord in field.stages
    }
    if placed_stages:
        minimum_placed_stage = min(placed_stages.values())
        maximum_placed_stage = max(placed_stages.values())
        stage_center = 0.5 * (minimum_placed_stage + maximum_placed_stage)
        stage_scale = max(1.0, float(maximum_placed_stage - minimum_placed_stage))
    else:
        stage_center = 0.0
        stage_scale = 1.0
    input_nodes = {int(node_id) for node_id in getattr(env, "input_nodes", ())}
    output_nodes = {int(node_id) for node_id in getattr(env, "output_nodes", ())}

    node_rows = []
    retrieval_node_hints = retrieval_node_hints or {}
    for node_id in node_ids:
        gate_one_hot = [0.0] * len(GATE_TYPE_NAMES)
        gate_index = _gate_type_index(env.circuit.getNodeTypeString(int(node_id)))
        if gate_index is not None:
            gate_one_hot[gate_index] = 1.0
        layer_idx = int(node_to_layer.get(node_id, 0))
        layer_nodes = layers[layer_idx] if 0 <= layer_idx < len(layers) else [node_id]
        rank = layer_nodes.index(node_id) if node_id in layer_nodes else 0
        x, y = positions[node_id]
        phase_one_hot = [0.0] * 4
        phase_assigned = 0.0
        stage_normalized = 0.0
        if field is not None and (x, y) in field.phases:
            phase = int(field.phase_at((x, y)))
            phase_one_hot[phase] = 1.0
            phase_assigned = 1.0
            stage_normalized = (float(field.stage_at((x, y))) - stage_center) / stage_scale
        embedding_score = float(getattr(env, "embedding_scores", {}).get(node_id, 0.5))
        raw_hint = list(retrieval_node_hints.get(node_id, (0.0, 0.0, 0.0)))
        if len(raw_hint) != 3:
            raise ValueError("retrieval node hints must contain x, y, confidence")
        node_rows.append(
            gate_one_hot
            + [
                float(len(env.circuit.get_fanins(node_id))) / 4.0,
                float(len(env.circuit.get_fanouts(node_id))) / 4.0,
                float(layer_idx) / max(1.0, float(len(layers) - 1)),
                float(rank) / max(1.0, float(len(layer_nodes) - 1)),
                (float(x) - center_x) / coord_norm,
                (float(y) - center_y) / coord_norm,
                float(node_id in input_nodes),
                float(node_id in output_nodes),
                embedding_score - 0.5,
            ]
            + phase_one_hot
            + [phase_assigned, stage_normalized]
            + [float(value) for value in raw_hint]
        )

    edge_pairs = []
    edge_rows = []
    layer_scale = max(1.0, float(len(layers) - 1))
    phase_count = max(1, int(getattr(env, "phase_cycle", 4)))
    for source, target in env.circuit.effective_edges:
        source = int(source)
        target = int(target)
        if source not in node_to_index or target not in node_to_index:
            continue
        edge_pairs.append((node_to_index[source], node_to_index[target]))
        source_layer = int(node_to_layer.get(source, 0))
        target_layer = int(node_to_layer.get(target, source_layer))
        layer_delta = target_layer - source_layer
        source_x, source_y = positions[source]
        target_x, target_y = positions[target]
        delta_x = int(target_x - source_x)
        delta_y = int(target_y - source_y)
        manhattan_distance = abs(delta_x) + abs(delta_y)
        clock_assigned = float(source in placed_stages and target in placed_stages)
        if clock_assigned:
            stage_delta = int(placed_stages[target] - placed_stages[source])
            phase_delta = (
                int(field.phase_at(positions[target]))
                - int(field.phase_at(positions[source]))
            ) % phase_count
            endpoint_feasible = float(0 <= stage_delta <= manhattan_distance)
        else:
            stage_delta = 0
            phase_delta = 0
            endpoint_feasible = 0.0
        edge_rows.append(
            [
                float(layer_delta) / layer_scale,
                float(abs(layer_delta) > 1),
                float(delta_x) / coord_norm,
                float(delta_y) / coord_norm,
                float(manhattan_distance) / coord_norm,
                float(phase_delta) / float(phase_count),
                float(stage_delta) / stage_scale,
                float(max(-2.0, min(2.0, stage_delta / max(1.0, float(manhattan_distance))))),
                endpoint_feasible,
                clock_assigned,
            ]
        )
    edge_index = (
        torch.tensor(edge_pairs, dtype=torch.long).t().contiguous()
        if edge_pairs
        else torch.empty((2, 0), dtype=torch.long)
    )
    edge_features = (
        torch.tensor(edge_rows, dtype=torch.float32)
        if edge_rows
        else torch.empty((0, EDGE_FEATURE_DIM), dtype=torch.float32)
    )

    raw_mask = list(bool(value) for value in env.get_action_mask())
    action_types = []
    action_rows = []
    memberships: list[tuple[int, int]] = []
    node_id_set = set(node_ids)
    for action_idx, original_def in enumerate(env.action_defs):
        concrete_def = original_def
        concretize = getattr(env, "_concretize_action", None)
        if callable(concretize):
            concrete_def = concretize(original_def)
        if concrete_def is None:
            raw_mask[action_idx] = False
            concrete_def = ("noop", -1, 0)
        action_name, _target, delta = concrete_def
        normalized_name = _normalize_action_name(action_name)
        action_type = _ACTION_TYPE_BY_NAME.get(normalized_name)
        if action_type is None:
            raw_mask[action_idx] = False
            action_type = LayoutActionType.NOOP
        target_nodes = _target_nodes_for_action(concrete_def, layers, node_id_set)
        target_layers = [node_to_layer[node_id] for node_id in target_nodes if node_id in node_to_layer]
        for node_id in sorted(set(target_nodes)):
            memberships.append((action_idx, node_to_index[node_id]))
        action_types.append(int(action_type))
        action_rows.append(
            [
                float(delta) / 6.0,
                float(len(set(target_nodes))) / max(1.0, float(len(node_ids))),
                float(sum(target_layers) / len(target_layers)) / max(1.0, float(len(layers) - 1))
                if target_layers
                else 0.0,
                float(len(set(target_nodes)) > 1),
            ]
        )

    action_target_index = (
        torch.tensor(memberships, dtype=torch.long).t().contiguous()
        if memberships
        else torch.empty((2, 0), dtype=torch.long)
    )
    policy_input = GraphPolicyInput(
        node_features=torch.tensor(node_rows, dtype=torch.float32),
        edge_index=edge_index,
        edge_features=edge_features,
        clock_features=_build_clock_features(env, field),
        action_types=torch.tensor(action_types, dtype=torch.long),
        action_features=torch.tensor(action_rows, dtype=torch.float32),
        action_target_index=action_target_index,
        action_mask=torch.tensor(raw_mask, dtype=torch.bool),
        retrieval_features=(
            torch.as_tensor(retrieval_features, dtype=torch.float32)
            if retrieval_features is not None
            else None
        ),
        episode_features=(
            torch.as_tensor(episode_features, dtype=torch.float32)
            if episode_features is not None
            else None
        ),
        memory_state=(
            torch.as_tensor(memory_state, dtype=torch.float32).detach().clone()
            if memory_state is not None
            else None
        ),
    )
    policy_input.validate()
    return policy_input


def sample_policy_action(
    model: UniversalGraphPolicy,
    policy_input: GraphPolicyInput,
    *,
    deterministic: bool = False,
) -> tuple[int, torch.Tensor, torch.Tensor]:
    distribution, value = model.distribution(policy_input)
    action = torch.argmax(distribution.logits) if deterministic else distribution.sample()
    return int(action.item()), distribution.log_prob(action), value


def predict_route_edge_priorities(
    model: UniversalGraphPolicy,
    env: Any,
    policy_input: GraphPolicyInput,
    device: torch.device | str,
) -> dict[tuple[int, int], float]:
    """Predict a hardest-first net order while retaining router fallbacks."""

    node_id_set = {int(node_id) for node_id in env.node_ids}
    valid_edges = [
        (int(source), int(target))
        for source, target in env.circuit.effective_edges
        if int(source) in node_id_set and int(target) in node_id_set
    ]
    with torch.no_grad():
        route_features = model.auxiliary_predictions(policy_input.to(device))["route"]
    if route_features.shape[0] != len(valid_edges):
        raise ValueError("route-priority output does not match the circuit edge count")
    if not route_features.numel():
        return {}
    # IFCN supervision: [length, turns, detour, ports, axis fractions, bbox].
    difficulty = (
        route_features[:, 0]
        + 0.75 * route_features[:, 1]
        + 0.75 * route_features[:, 2]
        + 0.25 * route_features[:, 9]
    )
    if not torch.isfinite(difficulty).all():
        raise FloatingPointError("non-finite learned route priorities")
    return {
        edge: float(score)
        for edge, score in zip(valid_edges, difficulty.detach().cpu().tolist())
    }
